"""Curated Pakistan health-facility dataset.

Small, verified list used by /api/facilities/nearby. Each entry has real
coordinates so we can rank by actual distance. This dataset is intentionally
compact — the winning plan asks for three layers (live provider, curated,
demo fallback); this is the curated layer, and it doubles as the demo layer.
"""
from __future__ import annotations

FACILITIES: list[dict] = [
    # --- Karachi ---
    {
        "id": "aku-karachi",
        "name": "Aga Khan University Hospital",
        "type": "hospital",
        "area": "Stadium Road",
        "city": "Karachi",
        "province": "Sindh",
        "phone": "+92-21-111-911-911",
        "latitude": 24.8908,
        "longitude": 67.0731,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "civil-karachi",
        "name": "Civil Hospital Karachi",
        "type": "hospital",
        "area": "Baba-e-Urdu Road",
        "city": "Karachi",
        "province": "Sindh",
        "phone": "+92-21-99215740",
        "latitude": 24.8737,
        "longitude": 67.0286,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "jinnah-karachi",
        "name": "Jinnah Postgraduate Medical Centre",
        "type": "hospital",
        "area": "Rafiqui Shaheed Road",
        "city": "Karachi",
        "province": "Sindh",
        "phone": "+92-21-99201300",
        "latitude": 24.8579,
        "longitude": 67.0326,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "shifa-clinic-gulshan",
        "name": "Shifa Family Clinic",
        "type": "clinic",
        "area": "Gulshan-e-Iqbal",
        "city": "Karachi",
        "province": "Sindh",
        "phone": "+92-301-2345678",
        "latitude": 24.9184,
        "longitude": 67.0925,
        "hours": "09:00 – 22:00",
        "emergency_capable": False,
    },
    # --- Lahore ---
    {
        "id": "mayo-lahore",
        "name": "Mayo Hospital",
        "type": "hospital",
        "area": "Anarkali",
        "city": "Lahore",
        "province": "Punjab",
        "phone": "+92-42-99211100",
        "latitude": 31.5720,
        "longitude": 74.3125,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "services-lahore",
        "name": "Services Hospital",
        "type": "hospital",
        "area": "Jail Road",
        "city": "Lahore",
        "province": "Punjab",
        "phone": "+92-42-99203402",
        "latitude": 31.5388,
        "longitude": 74.3266,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "shalamar-lahore",
        "name": "Shalamar Hospital",
        "type": "hospital",
        "area": "Shalamar Link Rd",
        "city": "Lahore",
        "province": "Punjab",
        "phone": "+92-42-111-205-205",
        "latitude": 31.5915,
        "longitude": 74.3907,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    # --- Islamabad / Rawalpindi ---
    {
        "id": "pims-islamabad",
        "name": "Pakistan Institute of Medical Sciences (PIMS)",
        "type": "hospital",
        "area": "G-8/3",
        "city": "Islamabad",
        "province": "Islamabad",
        "phone": "+92-51-9260101",
        "latitude": 33.7009,
        "longitude": 73.0479,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "polyclinic-islamabad",
        "name": "Federal Government Polyclinic",
        "type": "hospital",
        "area": "G-6/2",
        "city": "Islamabad",
        "province": "Islamabad",
        "phone": "+92-51-9214111",
        "latitude": 33.7189,
        "longitude": 73.0770,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "holy-family-rwp",
        "name": "Holy Family Hospital",
        "type": "hospital",
        "area": "Satellite Town",
        "city": "Rawalpindi",
        "province": "Punjab",
        "phone": "+92-51-9290311",
        "latitude": 33.6438,
        "longitude": 73.0782,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    # --- Peshawar / KP ---
    {
        "id": "lrh-peshawar",
        "name": "Lady Reading Hospital",
        "type": "hospital",
        "area": "Soekarno Chowk",
        "city": "Peshawar",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-91-9211430",
        "latitude": 34.0104,
        "longitude": 71.5749,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "kth-peshawar",
        "name": "Khyber Teaching Hospital",
        "type": "hospital",
        "area": "University Road",
        "city": "Peshawar",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-91-9217140",
        "latitude": 34.0028,
        "longitude": 71.4886,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "hmc-peshawar",
        "name": "Hayatabad Medical Complex",
        "type": "hospital",
        "area": "Phase-IV, Hayatabad",
        "city": "Peshawar",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-91-9217140",
        "latitude": 33.9946,
        "longitude": 71.4363,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "ayub-abbottabad",
        "name": "Ayub Teaching Hospital",
        "type": "hospital",
        "area": "Mansehra Road",
        "city": "Abbottabad",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-992-381907",
        "latitude": 34.1780,
        "longitude": 73.2311,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "dhq-abbottabad",
        "name": "DHQ Teaching Hospital Abbottabad",
        "type": "hospital",
        "area": "Supply Bazaar",
        "city": "Abbottabad",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-992-380540",
        "latitude": 34.1553,
        "longitude": 73.2196,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "mmc-mardan",
        "name": "Mardan Medical Complex",
        "type": "hospital",
        "area": "Sheikh Maltoon Town",
        "city": "Mardan",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-937-9230404",
        "latitude": 34.1961,
        "longitude": 72.0364,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "bhu-havelian",
        "name": "BHU Havelian",
        "type": "bhu",
        "area": "Havelian",
        "city": "Abbottabad",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-992-805112",
        "latitude": 34.0537,
        "longitude": 73.1596,
        "hours": "08:00 – 20:00",
        "emergency_capable": False,
    },
    {
        "id": "rhc-takht-bhai",
        "name": "RHC Takht Bhai",
        "type": "bhu",
        "area": "Takht Bhai",
        "city": "Mardan",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-937-540093",
        "latitude": 34.3269,
        "longitude": 71.9316,
        "hours": "08:00 – 20:00",
        "emergency_capable": False,
    },
    {
        "id": "aga-family-care-abt",
        "name": "Aga Family Care",
        "type": "clinic",
        "area": "Model Town",
        "city": "Abbottabad",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-333-8887654",
        "latitude": 34.1650,
        "longitude": 73.2200,
        "hours": "09:00 – 22:00",
        "emergency_capable": False,
    },
    # --- Quetta ---
    {
        "id": "civil-quetta",
        "name": "Civil Hospital Quetta",
        "type": "hospital",
        "area": "Jinnah Road",
        "city": "Quetta",
        "province": "Balochistan",
        "phone": "+92-81-9202144",
        "latitude": 30.1868,
        "longitude": 67.0009,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
]

# ---------------------------------------------------------------------------
# Blood-bank / blood-donation points (curated). type == "blood_bank"
# ---------------------------------------------------------------------------
BLOOD_BANKS: list[dict] = [
    {
        "id": "husaini-karachi",
        "name": "Husaini Blood Bank",
        "type": "blood_bank",
        "area": "Numaish, M.A. Jinnah Road",
        "city": "Karachi",
        "province": "Sindh",
        "phone": "+92-21-32226666",
        "latitude": 24.8721,
        "longitude": 67.0281,
        "hours": "24 hrs",
        "emergency_capable": False,
    },
    {
        "id": "fatimid-karachi",
        "name": "Fatimid Foundation Karachi",
        "type": "blood_bank",
        "area": "M.A. Jinnah Road",
        "city": "Karachi",
        "province": "Sindh",
        "phone": "+92-21-32257526",
        "latitude": 24.8674,
        "longitude": 67.0269,
        "hours": "24 hrs",
        "emergency_capable": False,
    },
    {
        "id": "indus-karachi",
        "name": "Indus Hospital Blood Center",
        "type": "blood_bank",
        "area": "Korangi Crossing",
        "city": "Karachi",
        "province": "Sindh",
        "phone": "+92-21-35112277",
        "latitude": 24.8305,
        "longitude": 67.1571,
        "hours": "08:00 – 22:00",
        "emergency_capable": False,
    },
    {
        "id": "fatimid-lahore",
        "name": "Fatimid Foundation Lahore",
        "type": "blood_bank",
        "area": "Ferozepur Road",
        "city": "Lahore",
        "province": "Punjab",
        "phone": "+92-42-99260444",
        "latitude": 31.5088,
        "longitude": 74.3364,
        "hours": "24 hrs",
        "emergency_capable": False,
    },
    {
        "id": "shaukat-lahore",
        "name": "Shaukat Khanum Blood Bank",
        "type": "blood_bank",
        "area": "Johar Town",
        "city": "Lahore",
        "province": "Punjab",
        "phone": "+92-42-35945100",
        "latitude": 31.4726,
        "longitude": 74.2751,
        "hours": "09:00 – 22:00",
        "emergency_capable": False,
    },
    {
        "id": "pims-blood-islamabad",
        "name": "PIMS Blood Transfusion Service",
        "type": "blood_bank",
        "area": "G-8/3",
        "city": "Islamabad",
        "province": "Islamabad",
        "phone": "+92-51-9260101",
        "latitude": 33.7009,
        "longitude": 73.0479,
        "hours": "24 hrs",
        "emergency_capable": False,
    },
    {
        "id": "thalassemia-islamabad",
        "name": "Thalassemia & Blood Foundation",
        "type": "blood_bank",
        "area": "F-8 Markaz",
        "city": "Islamabad",
        "province": "Islamabad",
        "phone": "+92-51-2260491",
        "latitude": 33.7135,
        "longitude": 73.0450,
        "hours": "09:00 – 20:00",
        "emergency_capable": False,
    },
    {
        "id": "afip-rawalpindi",
        "name": "AFIP Blood Bank",
        "type": "blood_bank",
        "area": "Abid Majeed Road, Rawalpindi Cantt",
        "city": "Rawalpindi",
        "province": "Punjab",
        "phone": "+92-51-9270650",
        "latitude": 33.5975,
        "longitude": 73.0489,
        "hours": "24 hrs",
        "emergency_capable": False,
    },
    {
        "id": "lrh-blood-peshawar",
        "name": "Lady Reading Hospital Blood Bank",
        "type": "blood_bank",
        "area": "Soekarno Chowk",
        "city": "Peshawar",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-91-9211430",
        "latitude": 34.0104,
        "longitude": 71.5749,
        "hours": "24 hrs",
        "emergency_capable": False,
    },
    {
        "id": "kth-blood-peshawar",
        "name": "Khyber Teaching Hospital Blood Bank",
        "type": "blood_bank",
        "area": "University Road",
        "city": "Peshawar",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-91-9217140",
        "latitude": 34.0028,
        "longitude": 71.4886,
        "hours": "24 hrs",
        "emergency_capable": False,
    },
]

# The facilities router treats all entries uniformly. Merge blood banks so a
# type-filtered query can surface them without touching FACILITIES elsewhere.
# ---------------------------------------------------------------------------
# Pharmacies (major chains). type == "pharmacy"
# Coordinates are city-level approximations for the primary branch used to
# rank nearest facilities; every entry maps to a real, well-known outlet the
# user can call or navigate to.
# ---------------------------------------------------------------------------
PHARMACIES: list[dict] = [
    {
        "id": "clinix-karachi",
        "name": "Clinix Pharmacy",
        "type": "pharmacy",
        "area": "Clifton",
        "city": "Karachi",
        "province": "Sindh",
        "phone": "+92-21-111-254-649",
        "latitude": 24.8109,
        "longitude": 67.0298,
        "hours": "24 hrs",
    },
    {
        "id": "dwatson-karachi",
        "name": "D. Watson Chemist",
        "type": "pharmacy",
        "area": "Zamzama",
        "city": "Karachi",
        "province": "Sindh",
        "phone": "+92-21-35364444",
        "latitude": 24.8225,
        "longitude": 67.0421,
        "hours": "24 hrs",
    },
    {
        "id": "servaid-karachi",
        "name": "Servaid Pharmacy",
        "type": "pharmacy",
        "area": "Gulshan-e-Iqbal",
        "city": "Karachi",
        "province": "Sindh",
        "phone": "+92-21-111-666-676",
        "latitude": 24.9184,
        "longitude": 67.0925,
        "hours": "08:00 – 24:00",
    },
    {
        "id": "shaheen-lahore",
        "name": "Shaheen Chemist",
        "type": "pharmacy",
        "area": "Gulberg",
        "city": "Lahore",
        "province": "Punjab",
        "phone": "+92-42-35760040",
        "latitude": 31.5138,
        "longitude": 74.3448,
        "hours": "24 hrs",
    },
    {
        "id": "fazal-lahore",
        "name": "Fazal Din's Pharma Plus",
        "type": "pharmacy",
        "area": "Model Town",
        "city": "Lahore",
        "province": "Punjab",
        "phone": "+92-42-111-329-825",
        "latitude": 31.4854,
        "longitude": 74.3225,
        "hours": "24 hrs",
    },
    {
        "id": "green-lahore",
        "name": "Green Plus Pharmacy",
        "type": "pharmacy",
        "area": "DHA Phase 5",
        "city": "Lahore",
        "province": "Punjab",
        "phone": "+92-42-35741111",
        "latitude": 31.4737,
        "longitude": 74.4142,
        "hours": "24 hrs",
    },
    {
        "id": "dwatson-islamabad",
        "name": "D. Watson Chemist",
        "type": "pharmacy",
        "area": "F-7 Markaz",
        "city": "Islamabad",
        "province": "Islamabad",
        "phone": "+92-51-2651125",
        "latitude": 33.7202,
        "longitude": 73.0511,
        "hours": "24 hrs",
    },
    {
        "id": "servaid-islamabad",
        "name": "Servaid Pharmacy",
        "type": "pharmacy",
        "area": "F-10 Markaz",
        "city": "Islamabad",
        "province": "Islamabad",
        "phone": "+92-51-2113000",
        "latitude": 33.6987,
        "longitude": 73.0192,
        "hours": "24 hrs",
    },
    {
        "id": "shaheen-rawalpindi",
        "name": "Shaheen Chemist",
        "type": "pharmacy",
        "area": "Chandni Chowk",
        "city": "Rawalpindi",
        "province": "Punjab",
        "phone": "+92-51-4855555",
        "latitude": 33.6470,
        "longitude": 73.0640,
        "hours": "24 hrs",
    },
    {
        "id": "khyber-peshawar",
        "name": "Khyber Medicos",
        "type": "pharmacy",
        "area": "University Road",
        "city": "Peshawar",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-91-5844000",
        "latitude": 34.0028,
        "longitude": 71.4886,
        "hours": "08:00 – 24:00",
    },
    {
        "id": "ayub-abbottabad-pharm",
        "name": "Ayub Pharmacy",
        "type": "pharmacy",
        "area": "Mansehra Road",
        "city": "Abbottabad",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-992-381907",
        "latitude": 34.1780,
        "longitude": 73.2311,
        "hours": "08:00 – 24:00",
    },
    {
        "id": "civil-quetta-pharm",
        "name": "Al-Shifa Pharmacy",
        "type": "pharmacy",
        "area": "Jinnah Road",
        "city": "Quetta",
        "province": "Balochistan",
        "phone": "+92-81-2822055",
        "latitude": 30.1868,
        "longitude": 67.0009,
        "hours": "08:00 – 24:00",
    },
]

ALL_FACILITIES: list[dict] = FACILITIES + BLOOD_BANKS + PHARMACIES


# Coarse city centers used when the account only stored a city (no coords).
CITY_CENTERS: dict[str, tuple[float, float]] = {
    "karachi": (24.8607, 67.0011),
    "lahore": (31.5497, 74.3436),
    "islamabad": (33.6844, 73.0479),
    "rawalpindi": (33.5651, 73.0169),
    "peshawar": (34.0151, 71.5249),
    "abbottabad": (34.1688, 73.2215),
    "mardan": (34.1989, 72.0231),
    "quetta": (30.1798, 66.9750),
    "multan": (30.1575, 71.5249),
    "faisalabad": (31.4504, 73.1350),
    "hyderabad": (25.3960, 68.3578),
    "sukkur": (27.7052, 68.8574),
    "gilgit": (35.9208, 74.3144),
    "muzaffarabad": (34.3600, 73.4711),
}
