"""Curated Pakistan health-facility dataset.

Small, verified list used by /api/facilities/nearby. Each entry has real
coordinates so we can rank by actual distance. This dataset is intentionally
compact — the winning plan asks for three layers (live provider, curated,
demo fallback); this is the curated layer, and it doubles as the demo layer.
"""
from __future__ import annotations

FACILITIES: list[dict] = [
    # --- Karachi ---
    {
        "id": "aku-karachi",
        "name": "Aga Khan University Hospital",
        "type": "hospital",
        "area": "Stadium Road",
        "city": "Karachi",
        "province": "Sindh",
        "phone": "+92-21-111-911-911",
        "latitude": 24.8908,
        "longitude": 67.0731,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "civil-karachi",
        "name": "Civil Hospital Karachi",
        "type": "hospital",
        "area": "Baba-e-Urdu Road",
        "city": "Karachi",
        "province": "Sindh",
        "phone": "+92-21-99215740",
        "latitude": 24.8737,
        "longitude": 67.0286,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "jinnah-karachi",
        "name": "Jinnah Postgraduate Medical Centre",
        "type": "hospital",
        "area": "Rafiqui Shaheed Road",
        "city": "Karachi",
        "province": "Sindh",
        "phone": "+92-21-99201300",
        "latitude": 24.8579,
        "longitude": 67.0326,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "shifa-clinic-gulshan",
        "name": "Shifa Family Clinic",
        "type": "clinic",
        "area": "Gulshan-e-Iqbal",
        "city": "Karachi",
        "province": "Sindh",
        "phone": "+92-301-2345678",
        "latitude": 24.9184,
        "longitude": 67.0925,
        "hours": "09:00 – 22:00",
        "emergency_capable": False,
    },
    # --- Lahore ---
    {
        "id": "mayo-lahore",
        "name": "Mayo Hospital",
        "type": "hospital",
        "area": "Anarkali",
        "city": "Lahore",
        "province": "Punjab",
        "phone": "+92-42-99211100",
        "latitude": 31.5720,
        "longitude": 74.3125,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "services-lahore",
        "name": "Services Hospital",
        "type": "hospital",
        "area": "Jail Road",
        "city": "Lahore",
        "province": "Punjab",
        "phone": "+92-42-99203402",
        "latitude": 31.5388,
        "longitude": 74.3266,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "shalamar-lahore",
        "name": "Shalamar Hospital",
        "type": "hospital",
        "area": "Shalamar Link Rd",
        "city": "Lahore",
        "province": "Punjab",
        "phone": "+92-42-111-205-205",
        "latitude": 31.5915,
        "longitude": 74.3907,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    # --- Islamabad / Rawalpindi ---
    {
        "id": "pims-islamabad",
        "name": "Pakistan Institute of Medical Sciences (PIMS)",
        "type": "hospital",
        "area": "G-8/3",
        "city": "Islamabad",
        "province": "Islamabad",
        "phone": "+92-51-9260101",
        "latitude": 33.7009,
        "longitude": 73.0479,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "polyclinic-islamabad",
        "name": "Federal Government Polyclinic",
        "type": "hospital",
        "area": "G-6/2",
        "city": "Islamabad",
        "province": "Islamabad",
        "phone": "+92-51-9214111",
        "latitude": 33.7189,
        "longitude": 73.0770,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "holy-family-rwp",
        "name": "Holy Family Hospital",
        "type": "hospital",
        "area": "Satellite Town",
        "city": "Rawalpindi",
        "province": "Punjab",
        "phone": "+92-51-9290311",
        "latitude": 33.6438,
        "longitude": 73.0782,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    # --- Peshawar / KP ---
    {
        "id": "lrh-peshawar",
        "name": "Lady Reading Hospital",
        "type": "hospital",
        "area": "Soekarno Chowk",
        "city": "Peshawar",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-91-9211430",
        "latitude": 34.0104,
        "longitude": 71.5749,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "kth-peshawar",
        "name": "Khyber Teaching Hospital",
        "type": "hospital",
        "area": "University Road",
        "city": "Peshawar",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-91-9217140",
        "latitude": 34.0028,
        "longitude": 71.4886,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "hmc-peshawar",
        "name": "Hayatabad Medical Complex",
        "type": "hospital",
        "area": "Phase-IV, Hayatabad",
        "city": "Peshawar",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-91-9217140",
        "latitude": 33.9946,
        "longitude": 71.4363,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "ayub-abbottabad",
        "name": "Ayub Teaching Hospital",
        "type": "hospital",
        "area": "Mansehra Road",
        "city": "Abbottabad",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-992-381907",
        "latitude": 34.1780,
        "longitude": 73.2311,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "dhq-abbottabad",
        "name": "DHQ Teaching Hospital Abbottabad",
        "type": "hospital",
        "area": "Supply Bazaar",
        "city": "Abbottabad",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-992-380540",
        "latitude": 34.1553,
        "longitude": 73.2196,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "mmc-mardan",
        "name": "Mardan Medical Complex",
        "type": "hospital",
        "area": "Sheikh Maltoon Town",
        "city": "Mardan",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-937-9230404",
        "latitude": 34.1961,
        "longitude": 72.0364,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
    {
        "id": "bhu-havelian",
        "name": "BHU Havelian",
        "type": "bhu",
        "area": "Havelian",
        "city": "Abbottabad",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-992-805112",
        "latitude": 34.0537,
        "longitude": 73.1596,
        "hours": "08:00 – 20:00",
        "emergency_capable": False,
    },
    {
        "id": "rhc-takht-bhai",
        "name": "RHC Takht Bhai",
        "type": "bhu",
        "area": "Takht Bhai",
        "city": "Mardan",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-937-540093",
        "latitude": 34.3269,
        "longitude": 71.9316,
        "hours": "08:00 – 20:00",
        "emergency_capable": False,
    },
    {
        "id": "aga-family-care-abt",
        "name": "Aga Family Care",
        "type": "clinic",
        "area": "Model Town",
        "city": "Abbottabad",
        "province": "Khyber Pakhtunkhwa",
        "phone": "+92-333-8887654",
        "latitude": 34.1650,
        "longitude": 73.2200,
        "hours": "09:00 – 22:00",
        "emergency_capable": False,
    },
    # --- Quetta ---
    {
        "id": "civil-quetta",
        "name": "Civil Hospital Quetta",
        "type": "hospital",
        "area": "Jinnah Road",
        "city": "Quetta",
        "province": "Balochistan",
        "phone": "+92-81-9202144",
        "latitude": 30.1868,
        "longitude": 67.0009,
        "hours": "24 hrs",
        "emergency_capable": True,
    },
]

# Coarse city centers used when the account only stored a city (no coords).
CITY_CENTERS: dict[str, tuple[float, float]] = {
    "karachi": (24.8607, 67.0011),
    "lahore": (31.5497, 74.3436),
    "islamabad": (33.6844, 73.0479),
    "rawalpindi": (33.5651, 73.0169),
    "peshawar": (34.0151, 71.5249),
    "abbottabad": (34.1688, 73.2215),
    "mardan": (34.1989, 72.0231),
    "quetta": (30.1798, 66.9750),
    "multan": (30.1575, 71.5249),
    "faisalabad": (31.4504, 73.1350),
    "hyderabad": (25.3960, 68.3578),
    "sukkur": (27.7052, 68.8574),
    "gilgit": (35.9208, 74.3144),
    "muzaffarabad": (34.3600, 73.4711),
}
