"""baseline schema

Revision ID: bc1f9e04e748
Revises: 
Create Date: 2026-08-26 17:49:21.058970
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1f9e04e748'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_phone'), ['phone'], unique=True)

    # Case-insensitive UNIQUE email, partial so multiple NULL emails are allowed.
    # (Autogenerate cannot render expression-based indexes, so it is added here.)
    op.create_index(
        'uq_accounts_email_lower',
        'accounts',
        [sa.text('lower(email)')],
        unique=True,
        sqlite_where=sa.text('email IS NOT NULL'),
        postgresql_where=sa.text('email IS NOT NULL'),
    )

    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=12), nullable=False),
    sa.Column('path', sa.String(length=180), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_logs_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_status_code'), ['status_code'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_profile_id'), ['profile_id'], unique=False)

    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=40), nullable=False),
    sa.Column('policy_version', sa.String(length=24), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_records_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_records_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_records_consent_type'), ['consent_type'], unique=False)

    op.create_table('location_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('province', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('permission_state', sa.String(length=24), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('manual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_preferences_account_id'), ['account_id'], unique=True)

    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('relation', sa.String(length=40), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('blood_group', sa.String(length=8), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('bp_recorded_at', sa.Date(), nullable=True),
    sa.Column('vitals_history', sa.JSON(), nullable=False),
    sa.Column('chronic_conditions', sa.JSON(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_self', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_account_id'), ['account_id'], unique=False)

    op.create_table('usage_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('active_seconds', sa.Integer(), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('last_path', sa.String(length=180), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'session_key', name='uq_usage_account_session')
    )
    with op.batch_alter_table('usage_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_sessions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_sessions_last_seen_at'), ['last_seen_at'], unique=False)

    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('destination', sa.String(length=160), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_codes_account_id'), ['account_id'], unique=False)

    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('strength', sa.String(length=60), nullable=True),
    sa.Column('frequency', sa.String(length=80), nullable=True),
    sa.Column('duration', sa.String(length=60), nullable=True),
    sa.Column('with_food', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('prescription_date', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicines_profile_id'), ['profile_id'], unique=False)

    op.create_table('timeline_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=200), nullable=True),
    sa.Column('level', sa.String(length=24), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_entries_profile_id'), ['profile_id'], unique=False)

    op.create_table('triage_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('turns', sa.JSON(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_level', sa.String(length=24), nullable=True),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('initial_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('triage_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_triage_sessions_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triage_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_triage_sessions_profile_id'))

    op.drop_table('triage_sessions')
    with op.batch_alter_table('timeline_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_entries_profile_id'))

    op.drop_table('timeline_entries')
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicines_profile_id'))

    op.drop_table('medicines')
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_codes_account_id'))

    op.drop_table('verification_codes')
    with op.batch_alter_table('usage_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_sessions_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_usage_sessions_account_id'))

    op.drop_table('usage_sessions')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_account_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('location_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_preferences_account_id'))

    op.drop_table('location_preferences')
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_records_consent_type'))
        batch_op.drop_index(batch_op.f('ix_consent_records_changed_at'))
        batch_op.drop_index(batch_op.f('ix_consent_records_account_id'))

    op.drop_table('consent_records')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_profile_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_account_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_logs_status_code'))
        batch_op.drop_index(batch_op.f('ix_request_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_request_logs_path'))
        batch_op.drop_index(batch_op.f('ix_request_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_request_logs_account_id'))

    op.drop_table('request_logs')
    op.drop_index('uq_accounts_email_lower', table_name='accounts')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_phone'))
        batch_op.drop_index(batch_op.f('ix_accounts_email'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
